### ISSUE TITLE
使用时弹出提示

### ISSUE THREAD

**Issue by hp1395816384** [aiguoli/SimpleList#1]
在使用的时候弹出“this application requires the windows app runtime version 1.3”这个提示，无法使用，查询到这么一个帖子https://cloud.tencent.com/developer/article/2296768

**Comment by aiguoli** [comment]
尝试过了，不行。可以考虑点击确定然后下载一个runtime
https://github.com/microsoft/WindowsAppSDK/issues/2597

**Comment by drw2005** [comment]
同样的问题，安装https://github.com/abbodi1406/vcredist 这个包还是不行，运行不起来。

另外，大佬考虑能否支持下WIN7？另外没有中文界面吗？

**Comment by aiguoli** [comment]
SDK runtime安装包在这里下载
https://learn.microsoft.com/zh-cn/windows/apps/windows-app-sdk/downloads

1.8.0以后的版本支持中文，只要你的系统设置是中文

关于win7，winui3官方说明是不会支持的，详见 https://github.com/microsoft/WindowsAppSDK/issues/78

**Comment by drw2005** [comment]
> 弹窗点击确定就可以跳转到runtime安装包下载页面，如果没跳转可以在这里下载，截至目前是1.4版本 https://learn.microsoft.com/zh-cn/windows/apps/windows-app-sdk/downloads
> 
> 1.8.0以后的版本支持中文，只要你的系统设置是中文
> 
> 关于win7，winui3官方说明是不会支持的，详见 [microsoft/WindowsAppSDK#78](https://github.com/microsoft/WindowsAppSDK/issues/78)

在win11下安装那个runtime安装包好像有问题，不知道是不是我个人的问题。

大佬可以参考一下这个，看看能否直接解决此类问题：
https://www.cnblogs.com/lindexi/p/17679785.html

**Comment by drw2005** [comment]
win11下安装这个包就能正常运行了：
https://aka.ms/windowsappsdk/1.4/latest/windowsappruntimeinstall-x64.exe

**Comment by ShelbyAlan** [comment]
> win11下安装这个包就能正常运行了： https://aka.ms/windowsappsdk/1.4/latest/windowsappruntimeinstall-x64.exe

没有用

**Comment by aiguoli** [comment]
> > win11下安装这个包就能正常运行了： https://aka.ms/windowsappsdk/1.4/latest/windowsappruntimeinstall-x64.exe
> 
> 没有用

新版本可以不下载运行时了，试试看
