### ISSUE TITLE
账户授权请求在哪里看？

### ISSUE THREAD

**Issue by daysplume** [aiguoli/SimpleList#4]
登录管理中心在企业应用和应用注册里都没看到有授权申请

**Comment by daysplume** [comment]
> 登录管理中心在企业应用和应用注册里都没看到有授权申请

管理账户已经给子账户访问权限，子账户登录登录提示需要权限审批，但未看到审批申请

**Comment by daysplume** [comment]
登录已解决，但闪退严重，点击文件栏登录后，切换其它选项再回去会闪退；退出软件再打开需要重新登录验证

**Comment by aiguoli** [comment]
`1.11.3`添加了账户缓存，也修复了闪退问题，试试
