### ISSUE TITLE
无法打开，如图

### ISSUE THREAD

**Issue by a1073661215** [aiguoli/SimpleList#6]
![2024-04-08_214828](https://github.com/aiguoli/SimpleList/assets/65440025/21472ae2-9f30-4d59-b0ee-6b6a0d32561f)
Windows 应用 SDK 1.5，也有尝试安装，还是一样弹窗。

**Comment by aiguoli** [comment]
新版本自包含了运行时，可以下载新版本试试看

关于自包含
https://learn.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained
